hpc<-read.table("./Data/household_power_consumption.txt",header = TRUE, sep = ";")
hpc[['datetime']] <- strptime(paste(hpc[['Date']],hpc[['Time']],sep=" "),format = "%d/%m/%Y %H:%M:%S")
mydata <- subset(hpc, Date %in% c("1/2/2007","2/2/2007"))
png("plot2.png", width=480, height=480)
with(mydata,plot(datetime,Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab=""))
dev.off()
