hpc<-read.table("./Data/household_power_consumption.txt",header = TRUE, sep = ";")
hpc[['datetime']] <- strptime(paste(hpc[['Date']],hpc[['Time']],sep=" "),format = "%d/%m/%Y %H:%M:%S")
mydata <- subset(hpc, Date %in% c("1/2/2007","2/2/2007"))
png("plot1.png", width=480, height=480)
hist(as.numeric(mydata$Global_active_power), xlab = "Global Active Power (kilowatts)", col="red", main = "Global Active Power")
dev.off()